input {
  file {
    path => "/home/ubuntu/AIOPS-Additional-Labs/Section-04-Practical-applications-of-ML-II/lab-03/network_traffic.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  json {
    source => "message"
  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "network-traffic-logstash"
  }

  stdout {
    codec => rubydebug
  }
}
