Vagrant.configure("2") do |config|

  config.vm.provider "docker" do |d|
    d.image = "ubuntu:20.04"
    d.remains_running = true
    d.has_ssh = false
    d.cmd = ["/bin/bash", "-c", "while true; do sleep 1000; done"]
  end

  config.vm.synced_folder ".", "/vagrant", disabled: false

end
