apiVersion: apps/v1

kind: Deployment

metadata:
  name: iris-model-deployment

spec:

  replicas: 2

  selector:
    matchLabels:
      app: iris-model

  template:

    metadata:
      labels:
        app: iris-model

    spec:

      containers:

      - name: iris-model-api

        image: iris-model-api:latest

        imagePullPolicy: Never

        ports:

        - containerPort: 5000
