#!/bin/bash

echo "Virtual WAN Testing Commands"
echo "Run these commands inside Mininet CLI:"
echo ""
echo "1. Check nodes:"
echo "nodes"
echo ""
echo "2. Check topology:"
echo "net"
echo ""
echo "3. Test all connectivity:"
echo "pingall"
echo ""
echo "4. Hub to branch tests:"
echo "h1 ping -c 3 h3"
echo "h1 ping -c 3 h4"
echo "h1 ping -c 3 h5"
echo ""
echo "5. Branch to branch tests:"
echo "h3 ping -c 3 h4"
echo "h4 ping -c 3 h5"
echo "h3 ping -c 3 h5"
echo ""
echo "6. Start iperf3 server:"
echo "h1 iperf3 -s &"
echo ""
echo "7. Bandwidth tests:"
echo "h3 iperf3 -c 10.0.1.10 -t 10"
echo "h4 iperf3 -c 10.0.1.10 -t 10"
echo "h5 iperf3 -c 10.0.1.10 -t 10"
